name: Jest Testing

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  unit-test:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.17.1"
      - run: npm install --legacy-peer-deps
      - name: Run a command with a specific time zone
        env:
          TZ: 'America/New_York'
        run: |
          echo "The current time is $(date)"
          npm test